apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: firstpo
  name: firstpo
  namespace: testfns
spec:
  containers:
  - image: nginx
    name: firstpo
    resources:
      limits:
        memory: "100M"
        cpu: "100m"
      requests:
        memory: "50M"
        cpu: "50m"
  restartPolicy: Always
